### ISSUE TITLE
[Epic] 4.1: Basic front end for node operator

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#100]
**Epic label**: `E:4.1: Basic front end for node operator`

# Summary

## Context and Need
Waku nodes currently lack a user-friendly interface, making it difficult for non-technical users to interact with the network.

## Objective
Provide a simple and non-technical means for users to interact with Waku nodes, enhancing usability, especially for workshops and new users.

### Proof of concept
The design for this front end should be developed at a proof of concept level.

# Deliverables
D1. Dockerized frontend with a nice design and some waku branding. Avoid using fancy frameworks that soon become obsolete. With the following features:

Integrated with [nwaku-compose](https://github.com/waku-org/nwaku-compose) so that after "docker-compose up -d" the front end is available to the user.

The front end allows to publish a message to a given content topic, inputting a set of fields. Using the REST API. Can take UTF-8 string or binary payload in hex format (using post_waku_v2_relay_v1_message)

The front end allows to subscribe to a given content topic, and messages are displayed real-time in there.

# Acceptance Criteria
- Frontend that fulfills the D1 requirements above

# RAID

## Dependencies

# Tasks

js-waku: 
- [x] https://github.com/waku-org/waku-frontend/issues/2
- [x] https://github.com/waku-org/waku-frontend/issues/12
- [x] https://github.com/waku-org/waku-frontend/issues/13
- [x] https://github.com/waku-org/waku-frontend/issues/14
- [x] https://github.com/waku-org/waku-frontend/issues/17
- [ ] non blocking follow-up - https://github.com/waku-org/waku-frontend/issues/8

nwaku:
- [x] https://github.com/waku-org/nwaku/issues/2223

**Comment by alrevuelta** [comment]
Related: https://github.com/waku-org/waku-frontend
Unfinished but tracked in that repo.

**Comment by weboko** [comment]
Weekly update:
_achieved_: follow ups and reduction of FE image;
_next_: double check with cors solved, minor improvements and fixes

**Comment by weboko** [comment]
@chair28980 keeping it open as per https://github.com/waku-org/nwaku/issues/2223#issuecomment-1850208223

**Comment by chair28980** [comment]
Closing per https://github.com/status-im/nim-presto/pull/68#issuecomment-1906406008

**Comment by alrevuelta** [comment]
Reopening since the frontend is not live in nwaku compose nor has the requested features. See deliverables section.

**Comment by Ivansete-status** [comment]
Closing as this is in https://github.com/waku-org/nwaku-compose
( cc @gabrielmer )
