### ISSUE TITLE
[Milestone] @waku/react launch

### ISSUE THREAD

**Issue by hackyguru** [waku-org/pm#104]
Requirements for launching `@waku/react` through social promotions :

- [x] Package available on npm (https://www.npmjs.com/package/@waku/react)
- [x] Amazing documentation is available (https://docs.waku.org/guides/js-waku/use-waku-react)
- [x] PR for fixing CRA was accepted  (https://github.com/ChainSafe/js-libp2p-noise/pull/388)
- [x] Non-chat example that uses the @waku/react package (https://github.com/hackyguru/tictactoe)
- [ ] Example needs to be migrated to examples repository
- [x] Blog needs to be published but it is already ready to be pushed after review
- [ ] PR for fixing CRA problem needs to be merged
- [ ] A video tutorial for using the react hooks (i'll complete this soon)
- [ ] Referencing the documentation on the npm package page
- [x] Rename the repository from 'waku-ui' to 'waku-react'

ETA : Before ETHIndia

**Comment by hackyguru** [comment]
Blog post PR : https://github.com/waku-org/blog.waku.org/pull/21
