### ISSUE TITLE
Status MVP: Multiple Communities + Token Gating

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#11]
**Deadline**: 31 Mar 2023

**High level requirement (Status)**:
- Start Dogfooding of Token Gating functionality on the Status CC community
- Other Logos projects (Codex, Nimbus, Vac, etc) switch to using Status
- Instances of Status Web with Token Gating functionality used for Logos and Status CC

**Impact on Waku**:
- Traffic increase due to more activity
- May expect slight increase of user
- Token Gating: no impact?
- Status Web usage: more light client protocols being used, this can be a major impact if light client protocols are **not** being used as part of https://github.com/waku-org/pm/issues/8

### Client Diversity

- 150 users use Status Desktop
- 150 users use Status Mobile
- 150 users use Status Web

Note1: at a given time, it is not expected that a user would use all clients at the same time.
Note2: there may be an increase of users as some Status CC may not have migrated to Status yet as they are using a different Discord Server
Note3: Usage of Status Web may be privileged by Status CC that could not use Status Desktop. We could may be assume that most Logos CC will use Status Web.

### Network Connectivity

- Status Web is expected to use light client protocols (filter, light client, store), they need to be served.
- Status Web can **only** connect via secure websocket with a valid, **not** self-signed certificate.
	- _Do we want to support inbound Status Web connection in Status Desktop?_: SSL  + WS + DyDNS
	- _Should we expect 100% Status Web nodes to connect to bootstrap fleet? What is the max connection setup on those nwaku nodes?_
	- _Do we need to start extending operator adoption so that nodes than can support wss connections can be added to the network and discovered by Status Web via discv5 + peer exchange?_

### Network Topology

- Fleet nodes provide store, lightpush and filter services
- Desktop clients provide lightpush and filter services and consume store services
	- _This assumes  WSS support with non-self signed certs in Status Desktop_
- Web clients consume lightpush, filter and store services
- Only WSS is supported by Web clients
- See pending questions from _Network Connectivity_

## Roadmap

- [ ] Review impact of token gating on Waku (assumed none).
- [ ] Review metrics requested by Status Web https://github.com/status-im/status-web/issues/310#issuecomment-1251505476
- [ ] Light Client Protocols readiness (to be updated depending on scope of #8)
- [ ] Understand connectivity picture with Status Web in scope.

**Comment by rymnc** [comment]
hey @fryorcraken is there some documentation on token gating's implementation? It is difficult to tell the impact of it upon Waku without that.

**Comment by fryorcraken** [comment]
I don't think it's defined at this stage. Cc @john-44 @cammellos
