### ISSUE TITLE
[Milestone] JSON RPC Deprecation

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#125]
**Milestone**:  https://github.com/waku-org/pm/milestone/14

# Summary
Deprecate nwaku and go-waku JSON RPC API and replace its usage with REST API across the repos (tests).

# Epics

- [x] js-waku: https://github.com/waku-org/pm/issues/140
- [x] nwaku: https://github.com/waku-org/pm/issues/146
- [ ] go-waku:
- [ ] QA: 
- [x] Docs: https://github.com/waku-org/pm/issues/151
- [ ] Eco-Dev:

**Comment by weboko** [comment]
On js-waku side we already dropped testing against `go-waku` and the only way we use JSON RPC is by retrieving some info or making nwaku do something from end-to-end tests that are in place. 

It should be safe to switch to REST but there are some risks involved:
- since testing happens from node.js runner - some packages sent might not be able to face issues that would happen in browser (example is the CORS issue https://github.com/waku-org/nwaku/issues/2223)
- some needs might not be covered just yet: ability to get some logs / statuses / responses while sending data;

Transition should be cautious and might need some back and forth with `nwaku` team.

Task for js-waku to work on - https://github.com/waku-org/js-waku/issues/1826

**Comment by chair28980** [comment]
Scope signed-off during EU-NA pm 2024-02-19.
