### ISSUE TITLE
[Epic: nwaku] PostgreSQL Maintenance

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#147]
Milestone-issue: https://github.com/waku-org/pm/issues/119

# Tasks
- [x] https://github.com/waku-org/nwaku/issues/1885
- [x] https://github.com/waku-org/nwaku/issues/2689
- [x] https://github.com/waku-org/nwaku/issues/2783 
- [x] https://github.com/waku-org/nwaku/issues/2807
- [ ] https://github.com/waku-org/nwaku/issues/2838

**Comment by fryorcraken** [comment]
Can we add to this [dashboard](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&refresh=30s&var-host=.%2A&var-fleet=status.prod&var-dc=All&viewPanel=77&from=now-7d&to=now&editPanel=77) the following graph(s):
- median query response time
- average query response time
- min query response time
- max query response time

Could be over a single graph or separate graph.

**Comment by Ivansete-status** [comment]
Great suggestion @fryorcraken ! I've created that one: https://github.com/waku-org/nwaku/issues/2995
