### ISSUE TITLE
[Epic] Waku Relay Topic Sharding: Static Sharding Implementation

### ISSUE THREAD

**Issue by kaiserd** [waku-org/pm#15]
This isssue is part of the [Status scaling MVP effort](https://github.com/waku-org/pm/issues/12) and tracks the *implementation* of the static sharding part of [51/WAKU2-RELAY-SHARDING](https://rfc.vac.dev/spec/51/).

## Acceptance Criteria

* [x] extend the ENR to support rshard clusters using the *One key per Shard Cluster* method (see RFC)
* [x] filtering logic to check if an ENR belongs to a node in a specific shard (i.e. pubsub topic)
* [x] associate peers to pubsub topics based on ENR (peer manager)

Client implementation issues:
- [x] js-waku: https://github.com/waku-org/js-waku/issues/1310
- [x] nwaku: https://github.com/waku-org/nwaku/issues/1643
- [x] go-waku: https://github.com/waku-org/pm/issues/15#issuecomment-1677844359

## Notes

* the RFC is still in raw state, needs field testing
* updates discussed and announced [here](https://github.com/vacp2p/research/issues/174) will be added to the RFC soon
* [update 31/WAKU2-ENR](https://github.com/vacp2p/research/issues/178)

**Comment by fryorcraken** [comment]
@richard-ramos is this done for go-waku? I guess so but was not clear what set of PR tracked the work.

**Comment by richard-ramos** [comment]
It is done in go-waku. The following merged PRs introduced such functionality:
- https://github.com/waku-org/go-waku/pull/522
- https://github.com/waku-org/go-waku/pull/563
- https://github.com/waku-org/go-waku/pull/574
- https://github.com/waku-org/go-waku/pull/576
- https://github.com/waku-org/go-waku/pull/595

**Comment by fryorcraken** [comment]
Static sharding available in all clients
