### ISSUE TITLE
[Epic: nwaku] Developer Experience Feedback

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#153]
Milestone-issue: https://github.com/waku-org/pm/issues/152

## Tasks

- [x] https://github.com/waku-org/nwaku/issues/2020
- [x] https://github.com/waku-org/nwaku/issues/2019
- [ ] https://github.com/waku-org/nwaku/issues/2270
- [x] https://github.com/waku-org/nwaku-compose/issues/57
- [ ] https://github.com/waku-org/nwaku/issues/2528
