### ISSUE TITLE
[Epic: js-waku] Waku React Native

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#155]
Milestone-issue: https://github.com/waku-org/pm/issues/124

## Tasks

- [x] Provide polyfills - https://github.com/waku-org/js-waku/pull/1915
- [ ] https://github.com/waku-org/js-waku/issues/628
- [ ] https://github.com/waku-org/js-waku/issues/1743

**Comment by weboko** [comment]
Once https://github.com/waku-org/js-waku/pull/1915 is merged we can move on with adding https://github.com/waku-org/lab.waku.org/pull/36

After it I will proceed with docs update that are on `js-waku` side.
