### ISSUE TITLE
[Epic: js-waku] Waku in the Browser on Unreliable Network

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#156]
Milestone-issue: https://github.com/waku-org/pm/issues/137

## Tasks

- provide local dev environment:
  - [ ] https://github.com/waku-org/js-waku/issues/1834;
- investigate and measure current websocket transport:
  - [ ] try to find problematic points: 2g internet, bad wifi (on/off etc);
  - [ ] search for mitigation;
- investigate ability to use HTTP transport in `libp2p`:
  - [ ] investigate if HTTP and long polling is possible;
  - [ ] implement if possible;

**Comment by chair28980** [comment]
https://github.com/waku-org/pm/issues/137#issuecomment-2123849347
