### ISSUE TITLE
[Epic: research] RLN in resource-restricted clients

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#160]
Milestone-issue: https://github.com/waku-org/pm/issues/159

## Tasks
- [ ] https://github.com/waku-org/research/issues/45
- [ ] https://github.com/waku-org/research/issues/72
- [ ] https://github.com/waku-org/research/issues/79

**Comment by alrevuelta** [comment]
With this summary, https://github.com/waku-org/research/issues/96 the research on RLN in resource-restricted clients is concluded. Now https://github.com/waku-org/pm/issues/168 tracks the shipping of this feature into The Waku Network.
