### ISSUE TITLE
[Epic: Dogfooding] Deliver RLN v2 + RLN in resource-restricted to The Waku Network

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/pm#168]
# Summary

Based on the work done on previous milestones that included both research and development:
* RLN v2 https://github.com/waku-org/pm/issues/163
* RLN in resource-restricted clients https://github.com/waku-org/pm/issues/159

This new milestone tracks the shipping of the above developed features i) RLNv2 and ii) RLN in resource-restricted clients into The Waku Network. See https://github.com/waku-org/research/issues/96 and https://github.com/waku-org/nwaku/issues/2345.

Note that both features are tracked together since they imply breaking changes in the smart contract.
* RLN v2 introduces `userMessageLimit` in membership registration.
* RLN in resource-restricted clients introduces a new function `merkleProofElements`.

Both changes will be introduced together to merge two backward incompatible changes into a single one, which has fewer effects on The Waku Network users.

# Epics

* research: 
  - [x] Come up with final gas estimation after the optimizations (RLN v2 +  RLN in resource-restricted). Here: https://github.com/waku-org/pm/issues/168#issuecomment-2199877022
  - [x] Implement changes in zerokit RLNv2 (>0.4.0) to support RLNv2 proof generation with custom witness: https://github.com/vacp2p/zerokit/pull/255
  - [x] Integrate RLNv2 into go-zerokit. Go allows to iterate faster and to develop testing tooling: https://github.com/waku-org/go-zerokit-rln/pull/21
  - [x] Integrate custom witness for RLNv2 in go-zerokit: https://github.com/waku-org/go-zerokit-rln/pull/22
  - [x] Deliver end-to-end PoC working in The Waku Network showcasing the new features. Based on https://github.com/alrevuelta/go-waku-light/ but currently doesn't support RLN v2.
      * PR: https://github.com/alrevuelta/go-waku-light/pull/5
* js-waku: 
  * Deprioritized by now in favor of https://github.com/waku-org/nwaku/issues/2593
* nwaku: 
  - [x] Update contract interface: https://github.com/waku-org/nwaku/pull/2770
  - [x] Make RLNv2 the default waku RLN, removing feature flag and RLN v1: https://github.com/waku-org/nwaku/pull/2828
  - [x] New smart contract with both RLNv2 and RLN in resource-restricted clients changes: https://github.com/waku-org/waku-rlnv2-contract
  - [x] bug: https://github.com/waku-org/nwaku/pull/2836
  - [x] bug: https://github.com/waku-org/nwaku/pull/2855
  - [x] chore: https://github.com/waku-org/nwaku/pull/2858/
  - [x] Decide epoch size (`rln-relay-epoch-sec`) and user message limit (`rln-relay-user-message-limit`) for TWN and set them in nwaku https://github.com/waku-org/nwaku/pull/2843
  - [x] ~~Deploy and consider using a L2 testnet. Deployed in PolygonzkEVM testnet: https://cardona-zkevm.polygonscan.com/address/0x4976df0f61135ef3e5720d92eade2e5f47a68ef9~~
  - [x] Due to some instability with PolygonzkEVM we decided to stick to Sepolia by now. Contract: https://sepolia.etherscan.io/address/0xCB33Aa5B38d79E3D9Fa8B10afF38AA201399a7e3
  - [x] Release v0.30.0 including RLNv2 + onchain trees. https://github.com/waku-org/nwaku/releases/tag/v0.30.0
  - [x] Release v0.30.1 containing some fixes: https://github.com/waku-org/nwaku/releases/tag/v0.30.1
  - [x] Deploy release to fleets, see multiaddress: https://github.com/waku-org/nwaku/pull/2872/files
  - [x] nwaku-compose changes to allow joining TWN with said configuration: https://github.com/waku-org/nwaku-compose/pull/103
  - [x] Deploy new instance of waku simulator to the host: https://github.com/waku-org/waku-simulator/pull/84
* go-waku:
* QA:
  - [x] Develop tooling in waku-simulator to allow rlnv2 testing: https://github.com/waku-org/waku-simulator/pull/45.
  - [x] Documentation to use waku-simulator for testing: https://waku-org.github.io/waku-simulator/
  - [x] Prepare testing plan for release v0.30.0 to test RLNv2 + onchain merkle trees: https://www.notion.so/Waku-RLNv2-End-to-End-Testing-with-Waku-simulator-6f50a5613eb44ae38e2dbbcfa72b7417
  - [x] Execute all tests on nwaku release candidate.
* Docs:
  - [x] Update TWN spec: https://github.com/vacp2p/rfc-index/pull/82
* Eco-Dev:
  - [x] Blog post announcing the new feature: https://github.com/waku-org/blog.waku.org/pull/60

**Comment by rymnc** [comment]
cc: @kaiserd, added vac acz milestone in https://github.com/logos-co/roadmap/pull/66/commits/986ebd59914f5e6790d48a622c09f19c95e6d33a

**Comment by alrevuelta** [comment]
Required changes in zerokit done and merged: https://github.com/vacp2p/zerokit/pull/255

**Comment by alrevuelta** [comment]
RLN v2 integrated in go-zerokit, done and merged: https://github.com/waku-org/go-zerokit-rln/pull/21
The main reason for integrating zerokit in go (go-zerokit) is that go allows to iterate faster and develop tooling for testing than in nim.

**Comment by alrevuelta** [comment]
>  Integrate custom witness for RLNv2 in go-zerokit

Done in https://github.com/waku-org/go-zerokit-rln/pull/22

**Comment by alrevuelta** [comment]
> Deliver end-to-end PoC working in The Waku Network showcasing the new features.

Done here: https://github.com/alrevuelta/go-waku-light/pull/5

**Comment by alrevuelta** [comment]
> New smart contract with both RLNv2 and RLN in resource-restricted clients changes:

Done by @rymnc here: https://github.com/waku-org/waku-rlnv2-contract

**Comment by alrevuelta** [comment]
> Develop tooling in waku-simulator to allow rlnv2 testing

Done by @stubbsta here: https://github.com/waku-org/waku-simulator/pull/45

**Comment by alrevuelta** [comment]
> Make RLNv2 the default waku RLN, removing feature flag and RLN v1

Done in here by @rymnc https://github.com/waku-org/nwaku/pull/2828

**Comment by alrevuelta** [comment]
> Prepare testing plan for release v0.30.0 to test RLNv2 + onchain merkle trees:

Done by @stubbsta in https://www.notion.so/Waku-RLNv2-End-to-End-Testing-with-Waku-simulator-6f50a5613eb44ae38e2dbbcfa72b7417

**Comment by alrevuelta** [comment]
> Documentation to use waku-simulator for testing

Done: https://waku-org.github.io/waku-simulator/

**Comment by alrevuelta** [comment]
> Deploy and consider using a L2 testnet.

Deployed in PolygonzkEVM testnet: https://cardona-zkevm.polygonscan.com/address/0x4976df0f61135ef3e5720d92eade2e5f47a68ef9 by @rymnc

**Comment by alrevuelta** [comment]
> Decide epoch size (rln-relay-epoch-sec) and user message limit (rln-relay-user-message-limit) for TWN

Done, parameters set for The Waku Network: https://github.com/waku-org/nwaku/pull/2843

**Comment by alrevuelta** [comment]
> bug fixed

https://github.com/waku-org/nwaku/pull/2855

**Comment by alrevuelta** [comment]
> Come up with final gas estimation after the optimizations (RLN v2 + RLN in resource-restricted)

Here we show the results of `forge test --gas-report -vv` of the `register` function. It shows the gas consumption of the call for different tree sizes.

With 100k memberships
<img width="676" alt="image" src="https://github.com/waku-org/pm/assets/8811422/edfdd872-bbaa-4bd3-bf5d-c12b2170dcaa">

With 10k memberships
<img width="681" alt="image" src="https://github.com/waku-org/pm/assets/8811422/085bbb68-c2df-4991-ba5f-2e77ee8d19f8">


In both cases:
* mean gas: 127k
* median gas: 83k
* some other higher value hits very rarely but stays withing some reasonable limits.

**Comment by alrevuelta** [comment]
> Release v0.30.0 including RLNv2 + onchain trees

Done here https://github.com/waku-org/nwaku/releases/tag/v0.30.0 by @Ivansete-status. Thanks for the help with the release.

**Comment by alrevuelta** [comment]
> nwaku-compose changes to allow joining TWN with said configuration:

Done. Now anyone can join the new version of TheWakuNetwork including rlnv2 and onchain merkle trees
https://github.com/waku-org/nwaku-compose/pull/103

**Comment by alrevuelta** [comment]
> Deploy release to fleets

Release 0.30.1 deployed by @Ivansete-status to TWN. See https://github.com/waku-org/nwaku/pull/2872/files for the multiaddresses of the bootstrap nodes.

**Comment by alrevuelta** [comment]
> Due to some instability with PolygonzkEVM we decided to stick to Sepolia by now.
> Release v0.30.1 containing some fixes:

* Fixes in v0.30.1:  https://github.com/waku-org/nwaku/releases/tag/v0.30.1
* Contract in sepolia: https://sepolia.etherscan.io/address/0xCB33Aa5B38d79E3D9Fa8B10afF38AA201399a7e3

**Comment by alrevuelta** [comment]
> Deploy new instance of waku simulator to the host

Feature deployed to waku-simulator by @stubbsta https://github.com/waku-org/waku-simulator/pull/84. RLNv2 + onchain trees is live in the private testnet of waku-simulator:
* https://explorer.waku.org/dashboard
* https://simulator.waku.org/

**Comment by alrevuelta** [comment]
> The Waku Network spec updated with RLNv2 and new parameters

https://github.com/vacp2p/rfc-index/pull/82

**Comment by alrevuelta** [comment]
> Blog post announcing the new feature

https://github.com/waku-org/blog.waku.org/pull/60
Live at: https://blog.waku.org/rln-v2-stateless-light-clients

**Comment by alrevuelta** [comment]
RLN-V2+ stateless light clients features are live in The Waku Network. I consider this epic closed. Thanks to anyone involved in making this happen!
