### ISSUE TITLE
[Deliverable] Enable testing of direct messages in unreliable networks

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#176]
## Tasks

- [ ] https://github.com/status-im/status-go/issues/5143
- [ ] https://github.com/status-im/status-go/issues/5144
- [ ] https://github.com/status-im/status-go/issues/5147
- [ ] https://github.com/status-im/status-go/issues/5234

**Comment by fryorcraken** [comment]
@plopezlpz Are we done with this?
I believe Vac/QA had some more test re suspend.
Note that communities on custom shards is tracked separately.

If Vac/QA is done then we can probably close this. @jm-clius @fbarbu15 please help clarify.

**Comment by chair28980** [comment]
@fbarbu15 anyone can create requisite issues, I'm responsible for keeping things labeled and ensuring the parent/child issues are tracked appropriately.

These are the MIlestones we have for the above mentioned items:
- https://github.com/waku-org/pm/milestone/28
- https://github.com/waku-org/pm/milestone/29
- https://github.com/waku-org/pm/milestone/30
- all Milestones: https://github.com/waku-org/pm/milestones

**Comment by fryorcraken** [comment]
@fbarbu15 any preferences of were you'd like to see those epics created?

## Review the current test coverage of chat functionalities in status-go and proceed with further coverage.

This item was included because of:

> 3. Static Sharding - dedicated shards
>  Add coverage of community creation and message sending on dedicated shards, including opt-in message signing DoS protection.

The static sharding item seems necessary because Status-QA has reported issues with communities on dedicated shards ("everything break").

The role of this present item is to have a good base in terms of testing so that when tackling coverage for dedicated sharding, you don't start from scratch.

I expect here to review https://rfc.vac.dev/status/55/1to1-chat and https://rfc.vac.dev/status/56/communities and ensure that coverage is appropriate.

@plopezlpz @kaichaosun @cammellos @richard-ramos  what are your thoughts on this matter?

## Review testing in status-go related to chat functionalities that rely on external systems (e.g., Waku fleet) and migrate them to an interoperable testing framework.

My understanding is that a number of tests as part of status-go CI are executed against live fleet, leading to regular failure during the CI.
This was mention during a status test meeting at Montenegro. @cammellos and @igor-sirotin seemed to be the most vocal about it. (cc @iurimatias @jrainville).

The intent here was to spend dedicated time to stabilize status-go CI to help with development in general.
It is my opinion that CI should be self-contained to avoid failure due to reasons other than the PR changes, hence a proposal to move the test against external fleets to another framework, which can then be run nightly.

However, I have no development on status-go so best if I get some input from people tagged above.

**Comment by igor-sirotin** [comment]
> My understanding is that a number of tests as part of status-go CI are executed against live fleet, leading to regular failure during the CI

Yes. I don't think there're many of them though.
Most messaging tests (`protocol` package) share a single Waku V1 node for several `Messenger`. These tests are not affected by the state of real fleets.

Here's a list of tests that I think use real fleet:
- `TestRestartDiscoveryV5`
- `TestRendezvousDiscovery`
- `TestWakuV2Filter`
- some more tests in `wakuv2/waku_test.go`

> It is my opinion that CI should be self-contained to avoid failure due to reasons other than the PR changes

👍 👍 ❤️

**Comment by igor-sirotin** [comment]
Just found another test that connects to the outer world:
- `TestPeerCount`

**Comment by fryorcraken** [comment]
@plopezlpz Happy to close this?
