### ISSUE TITLE
[Epic: nwaku] Telemetry: fleet logging

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#181]
## Tasks

- [x] https://github.com/waku-org/nwaku/pull/2973
- [x] https://github.com/waku-org/nwaku/pull/2737
- [x] https://github.com/waku-org/nwaku/pull/2403 ( this add logs to track sync operations )
- [x] https://github.com/waku-org/nwaku/pull/2640
- [x] https://github.com/waku-org/nwaku/pull/2969
- [x] https://github.com/waku-org/nwaku/pull/2951

**Comment by Ivansete-status** [comment]
Evidence of the epic completion, I'm adding some screenshots obtained from _Kibana_

![image](https://github.com/user-attachments/assets/7115729d-903b-4131-a5ee-19e8043c6cd1)

![image](https://github.com/user-attachments/assets/8e49972f-4450-4bd8-8b35-571248f50199)

![image](https://github.com/user-attachments/assets/0f2badb9-18c9-455f-bbab-dbb904c68ed9)

![image](https://github.com/user-attachments/assets/d6a278d7-69a6-4c8f-aa14-ab7b23e622e1)

![image](https://github.com/user-attachments/assets/4f5defee-bdb9-42ac-8a82-7ba875edc329)

![image](https://github.com/user-attachments/assets/337a5aff-472d-40aa-a341-2e9859631aa2)

![image](https://github.com/user-attachments/assets/3c4fb13b-aeab-40c9-9dd5-28634d22830c)

![image](https://github.com/user-attachments/assets/5c757b03-0005-4537-b16a-5d7cfc9359b5)

![image](https://github.com/user-attachments/assets/8116d92f-9c07-4b03-adeb-ad2952a3be5a)

![image](https://github.com/user-attachments/assets/de5a6417-cb8b-4aa9-b8a1-015e03b91314)

![image](https://github.com/user-attachments/assets/3cd7c02b-cabd-41b5-9ecd-c90cbba287bd)

![image](https://github.com/user-attachments/assets/970f643e-839e-4324-b898-1c68b72c4556)

![image](https://github.com/user-attachments/assets/a962e2df-00cd-44d9-88f0-c0d322ef30ac)

![image](https://github.com/user-attachments/assets/5035cf11-d631-4bdc-944f-40544a792ec0)

![image](https://github.com/user-attachments/assets/1be9fd66-158e-46c6-8cfc-a30b8e7caef5)
