### ISSUE TITLE
[Deliverable] Telemetry: direct message reliability

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#182]
## Work breakdown

- [ ] Report number of connected peers, including platform and app version information
- [ ] Provide graphs to see average/median/min/max time of reaching 10 connected peers per platform and version
- [ ] report dial failure, including used transport to measure efficacy of circuit relay
- [ ] report number of new messages learned via periodic store query, then filter by messages of interest for user
- [ ] Report store confirmation failures, assuming store confirmation only happen when message sending is initially reported as successful. Confirmation failure report should also include waku protocol used to send message (relay vs light push)

## Epics

- [x] https://github.com/waku-org/nwaku/issues/3081
- [x] https://github.com/waku-org/pm/issues/221

## Output

**Comment by fryorcraken** [comment]
Dashboard so far: https://superset.bi.status.im/superset/dashboard/68/?native_filters_key=GwCJxw65uC286F_iiwTkTKVGvz-3-dqJCFkWryZaiYTLvZ4C3jHP8v0lVBj34RiF

**Comment by fryorcraken** [comment]
Done.
