### ISSUE TITLE
[Deliverable] Reliability Protocol for Resource-Restricted Clients

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#186]
Project board: https://github.com/orgs/waku-org/projects/31/views/1

## Epics

- nwaku
- js-waku
- go-waku
- Status
- QA
- Testing
- Docs
- Dogfooding

**Comment by weboko** [comment]
Updated end date to 13/09/2024 to wait for @danisharora099 from vacation.

Following items are leftovers that are WIP now with ready PRs:
- [ ] Improve peer selection: https://github.com/waku-org/js-waku/issues/2074
- [ ] Message verification and retry: https://github.com/waku-org/js-waku/issues/2075
- [ ] Message retry for LightPush: https://github.com/waku-org/js-waku/issues/2069

**Comment by weboko** [comment]
From PoV of js-waku we can resolve this deliverable as per comment - https://github.com/waku-org/pm/issues/143#issuecomment-2355380525

Only important thing would be to follow up after `nwaku` migration to `LigthPush v2` is done. 

@Ivansete-status there are two items that are not resolved on `nwaku` side and I am not sure how it is intended to be approached:
- https://github.com/waku-org/nwaku/issues/2722
- https://github.com/waku-org/pm/issues/93

@fryorcraken @chair28980

**Comment by Ivansete-status** [comment]
morning @weboko et al - @NagyZoltanPeter is currently working on those enhancements

**Comment by fryorcraken** [comment]
One of the lesson was that the p2p tunable reliability strategies used for edge and relay nodes are very similar.

Hence, I suggest we clean up and merge the following specs together:

- https://github.com/waku-org/specs/blob/master/standards/application/transport-reliability.md
- https://github.com/waku-org/specs/blob/master/standards/application/req-res-reliability.md

Into one "Tunable Peer-to-Peer Reliability" spec. (see https://blog.waku.org/2024-06-20-message-reliability/ on how we differentiate transport and p2p reliability spec).

Code extract should also be removed in favour of plain English.

**Comment by chair28980** [comment]
Closing this Deliverable as all Epics have been completed. cc @fryorcraken @Ivansete-status @jm-clius
