### ISSUE TITLE
[Deliverable] Telemetry: Measure Bandwidth

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#195]
## Tasks
- [ ] https://github.com/status-im/telemetry/issues/62
- [ ] https://github.com/status-im/telemetry/pull/74
- [ ] https://github.com/status-im/status-go/pull/6176
- [ ] https://github.com/status-im/telemetry/pull/70
- [ ] https://github.com/status-im/status-go/pull/5973

**Comment by fryorcraken** [comment]
Telemetry is not the best way to go about bandwidth usage. The usage of local Prometheus metrics and Vac-DST is preferred. see https://forum.vac.dev/t/the-future-of-status-telemetry/405/4
