### ISSUE TITLE
[Epic] Opt-in message signing for custom topics

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/pm#20]
In order to have a short term and easy to implement fix for Denial of Service protection for the Status MVP, we have decided to add message validation for specific pubsub topics, configurable by the node operator. Message validation is perfermed by only relaying messages that are signed with a given private key. Only holders of said private key can publish valid messages. The public key equivalent is configured by the operators in given pubsub topics, which is ued to verify the message signature, which is an app level specific field used by the protocol.

Note that this is an *ad hoc* solution for status mvp and not part of the core protocol. Waku topics like the default pubsub topic will remain unchanged. This is the way of archiving DoS protection for Status MVP while having a minimum impact in the protocol.

Summary of changes:
* Implement message gossipsub message validation. Messages with a valid signature (see public key) are Accepted, otherwise Rejected.
* Nodes can configure via cli (or other methods) the public key that is used in each gossipsub topic.
* Add metrics to add obsevability on the number of accepted/rejected messages.
* (Optional by now) Enable libp2p scoring and disconnect from peers sending multiple invalid messages (see score)

## Requirements

* See [STATUS/57](https://rfc.vac.dev/spec/57/#dos-protection) spec for reference.

nwaku:
- [x] https://github.com/waku-org/nwaku/pull/1614
- [x] https://github.com/waku-org/nwaku/pull/1713
- [x] https://github.com/waku-org/nwaku/pull/1711
- [x] https://github.com/waku-org/nwaku/pull/1704
- [x] https://github.com/waku-org/nwaku/pull/1696

js-waku:
- [x] https://github.com/waku-org/js-waku/issues/1323

go-waku:
- [x] https://github.com/waku-org/go-waku/pull/535
- [x] https://github.com/waku-org/go-waku/pull/528
- [x] https://github.com/waku-org/go-waku/pull/504

(to be updated, with more)

**Comment by fryorcraken** [comment]
Done
