### ISSUE TITLE
[Deliverable] DoS protection for req-res protocols and metrics (go-waku as service node)

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#200]
## Tasks

- [x] https://github.com/waku-org/go-waku/pull/1258
- [x] https://github.com/status-im/status-go/pull/5504
- [x] https://github.com/status-im/status-go/pull/5504
- [x] https://github.com/status-im/status-go/pull/5964 (bug fix)

**Comment by richard-ramos** [comment]
Looking at the code, the rate limit is set for lightpush and peer-exchange. 
Both of these with 1 request per second. 

This was added 4 months ago in the following PRs (cc: @vpavlin)
https://github.com/status-im/status-go/pull/5504
https://github.com/status-im/status-go/pull/5504

These are available since release v2.30

It's missing for filter. Should be relatively straightfwd to implement so we get it on the next release.

**Comment by fryorcraken** [comment]
cc @chaitanyaprem should we review the 1 req per sec to a higher limit?

**Comment by chaitanyaprem** [comment]
> cc [@chaitanyaprem](https://github.com/chaitanyaprem) should we review the 1 req per sec to a higher limit?

I have already increased for publishing and filter side. Will have to increase for lightpush service-node side as well until we bring in rln.

**Comment by chair28980** [comment]
Re-opening pending testing.

**Comment by fryorcraken** [comment]
@plopezlpz is this done?
