### ISSUE TITLE
[Epic: Status] Enable testing of direct messages in unreliable networks

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#209]
## Tasks

- [ ] https://github.com/status-im/status-go/issues/5143
- [ ] https://github.com/status-im/status-go/issues/5144
- [ ] https://github.com/status-im/status-go/issues/5147
- [ ] https://github.com/status-im/status-go/issues/5234
