### ISSUE TITLE
[Epic: Status] Review connection management strategy & back-off & long disconnection issues

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#210]
## Tasks

- [x] https://github.com/status-im/status-go/issues/5412
- [x] https://github.com/status-im/status-go/pull/5281
- [x] https://github.com/status-im/status-go/issues/5147
