### ISSUE TITLE
[Epic: Status] Sharding peer management and discovery hardening

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#213]
## Tasks

- [x] https://github.com/waku-org/go-waku/pull/1194
- [x] https://github.com/waku-org/go-waku/pull/1193
- [x] https://github.com/waku-org/go-waku/pull/1214

**Comment by chaitanyaprem** [comment]
https://github.com/status-im/status-go/issues/5171 may not be needed to be part of this deliverable.
Since to achieve static sharding of communities with 100 shards , the existing fleet (maybe additional nodes) is going to support all shards (100 + 2 common) along with store nodes in the fleet.

@fryorcraken can you confirm?

**Comment by fryorcraken** [comment]
> [status-im/status-go#5171](https://github.com/status-im/status-go/issues/5171) may not be needed to be part of this deliverable. Since to achieve static sharding of communities with 100 shards , the existing fleet (maybe additional nodes) is going to support all shards (100 + 2 common) along with store nodes in the fleet.
> 
> @fryorcraken can you confirm?

Correct.

Fo r[Milestone Static Sharding - dedicated shards](https://github.com/waku-org/pm/milestone/30) we assume up to 100 shards/communities, all hosted by Status. Hence no need to remove hardcoding of store node.

Removal of hardcoding would be needed for [Milestone Scale up number of Communities](https://github.com/waku-org/pm/milestone/32)](https://github.com/waku-org/pm/milestone/32) but we have not yet scheduled this milestone.

**Comment by chaitanyaprem** [comment]
removed https://github.com/waku-org/go-waku/issues/1156 as per https://github.com/waku-org/go-waku/issues/1156#issuecomment-2328294568

**Comment by chaitanyaprem** [comment]
Nothing else pending in this milestone , so we can close it.

cc @chair28980 @fryorcraken

**Comment by fryorcraken** [comment]
Epics can be closed by CC or leads
