### ISSUE TITLE
[Epic: Status] Review MVDS usage and fail path

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#215]
## Tasks

- [x] Reset backoff MVDS epoch when receiver comes online: https://github.com/status-im/mvds/pull/5
- [x] List and consider MVDS message type usage: https://github.com/status-im/status-go/issues/5462
- [x] https://github.com/status-im/status-go/issues/5693
- [x] https://github.com/status-im/status-go/issues/5694

**Comment by kaichaosun** [comment]
- [x] https://github.com/status-im/status-go/pull/5787
