### ISSUE TITLE
[Epic: Status] Reliability Protocol for Resource-Restricted Clients

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#219]
## Tasks

- [x] https://github.com/status-im/status-desktop/pull/15061
- [x] https://github.com/status-im/status-go/pull/4665
- [x] https://github.com/status-im/status-go/pull/5350
- [x] https://github.com/waku-org/go-waku/pull/1130
- [x] https://github.com/waku-org/go-waku/pull/1129
- [x] https://github.com/waku-org/go-waku/pull/1128
- [x] https://github.com/waku-org/go-waku/pull/1134
- [x] https://github.com/status-im/status-go/issues/5355
- [x] https://github.com/status-im/status-go/issues/5262
- [x] https://github.com/status-im/status-go/issues/4857
- [x] https://github.com/status-im/status-go/pull/5474
- [x] https://github.com/waku-org/go-waku/pull/1163

**Comment by chaitanyaprem** [comment]
@chair28980 we can consider this as done from Status point of view. I have removed few items from the list above as they may not be required. 
Anything else will be covered as issues that need fixing.
