### ISSUE TITLE
[Milestone] Restricted-run (light node) protocols are production ready

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#25]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**Milestone label:** `E:2023-light-protocols`
**Priority Tracks**: Production Readiness
**Due date**: 30 Jul 2023

# Summary

> - Enabling a decentralized yet reliable experience in the browser and mobile (Status mobile).>
> - Hardening includes round of dogfooding with partner platforms such as Status, review of the protocol and reliability with inclusion in the quality process (non-regression, interop, performance)
> - Includes delivery of https://github.com/waku-org/pm/issues/8

# Justification

This milestone is critical for two of the 2023 tracks:

**Growth**

Waku Marketing Strategy and BD plan for 2023 is to focus:
- growing developer community
- onboarding early stage project

To onboard developers, the developer experience needs to be friction-less and allows fast result, quick ways to build PoCs.
Such dev ex enables developer to easily try and tinker with Waku, build with Waku during hackathons, be onboarded on Waku via workshops, guide and videos.

The easiest way to do so is to focus on the web ecosystem. JavaScript is the most used language and web app enables developers to quickly build visual PoC (in opposition to system languages).

Finally, because webapps are easiest and faster to build, developer and projects wishing to test out Waku, are likely to do so with a webapp first, even if their product offering include native apps, as it is usually a more cost effective way to execute a bet.
Hence, the overall developer experience, from onboarding to reliability, is critical for webapps to execute our growth milestone.

Finally, Webapps are restricted-resource nodes which relies on light node protocols.

**Production Readiness**

In the production readiness track, relay nodes take priorities from a fundamental standpoint: they are the backbone of the Waku network. Without reliable relay nodes, there is no reliable Waku network.

However, the web3 ecosystem is dominated by web and mobile apps. Which means that early projects adopting Waku are likely to need integrating Waku to a mobile or web (or both) app. Which is why production readiness of light client protocols must be a focus once production readiness of protocols fundamental to the relay network are delivered.

# Key Dates

## Status Communities on Status Mobile

Context: Usage of Waku on Status Mobile requires production ready light client protocols for reliable experience.
Issue: https://github.com/waku-org/pm/issues/8
Deadline: ~Feb 2023~ (integration work in Status Mobile only started in June, deadline was not officially revisited).

## Web3Conf India

Context: 3-4k developers are expected to join the conference and we intend to list prizes to the hackathon. Which means we need to expect a high volume of js-waku nodes during this period of time. https://web3confindia.xyz/
Issue: N/A
Deadline: 10 Aug 2023

# Epics

  - [ ] js-waku: [Peer Exchange is supported and used by default](https://github.com/waku-org/js-waku/issues/1429)
  - ~[ ] go-waku: [Add Light client interop tests ](https://github.com/waku-org/go-waku/issues/608)~
  - [x] pm: [Nwaku maximum connections reached for wss clients](https://github.com/waku-org/pm/issues/23)
  - [x] pm: [Status MVP: Status Core Contributors use Status Mobile](https://github.com/waku-org/pm/issues/8)
  - [x] pm: [Waku Filter and Lightpush: Evaluation and improvement](https://github.com/waku-org/pm/issues/5)

**Comment by fryorcraken** [comment]
**Monthly update**

More extensive dogfooding done in js-waku for Waku Peer Exchange. Results are mostly positive and peer exchange is now being set as a default peer discovery protocol in js-waku.
Status has integrated light push and filter protocol in Mobile and Desktop. Further testing is being done with Status Mobile.

**Comment by fryorcraken** [comment]
@jm-clius do you think much more belong to this milestone?

One missing part would be to onboard thousands of users on light clients but this seems to be more in the peer management and 1 mil user scopes.

**Comment by jm-clius** [comment]
> One missing part would be to onboard thousands of users on light clients

Agree that this would be part of other scopes. I'd say if js-waku is happy with the state of Waku Peer Exchange, we could probably close this issue.

**Comment by DeBelg** [comment]
Would you say this is the completion of Milestone 2.1 on https://github.com/waku-org/research/issues/3 
?

**Comment by fryorcraken** [comment]
> Would you say this is the completion of Milestone 2.1 on [waku-org/research#3](https://github.com/waku-org/research/issues/3) ?

We will close this milestone soon see https://github.com/waku-org/pm/pull/48
