### ISSUE TITLE
[Milestone] Peer management strategy for relay and light nodes are defined and implemented

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#33]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**Milestone label**: `E:2023-peer-mgmt`
**Priority Tracks**: Production Readiness
**Due date**: 31 Aug 2023

# Summary

1. suitable discovery methods to find new peers
2. some mechanism to score peers/be biased towards more reliable connections
3. connection management to establish, maintain and re-establish a large, healthy set of connections to peer decisions re peer persistence
4. strategies and measurements around peer connectivity restrictions (e.g. NAT traversal, uni- vs bidirectionality of connections, etc.)

# Justification

Proper peer and connection management is crucial to ensure reliable message delivery in a Waku network, due to nature of relay. A strong relayer network is the most basic underpinning of any Waku v2 network. All other Waku services builds on the assumption that the underlying message routing works well and is scalable. For example, each peer in the network must be able to establish and maintain at least six good connections to other peers. Read [this summary](https://forum.vac.dev/t/towards-a-working-waku-v2-infrastructure/154#waku-relay-the-foundation-of-any-waku-v2-network-2) for what would constitute a "good" connection.

Resource-restricted devices, with limited bandwidth or mostly offline need efficient connection management to ensure that reliable connections are set from the moment the app is started or has network access.

# Epics

  - [ ] nwaku: [Sharded peer management and discovery](https://github.com/waku-org/nwaku/issues/1919)
  - [ ] js-waku: [Peer Management: Automated actions upon reconnection](https://github.com/waku-org/js-waku/issues/1464)
  - [ ] js-waku: [Peer Management: Scoring, Redundancy and Persistence](https://github.com/waku-org/js-waku/issues/1463)
  - [ ] js-waku: [Peer Management: Connection and Disconnection](https://github.com/waku-org/js-waku/issues/914)
  - [ ] go-waku: [Introduce Peer Management](https://github.com/waku-org/go-waku/issues/594)

**Comment by fryorcraken** [comment]
**monthly update**

Peer management has been implemented in go-waku, dogfooding with Status Desktop is the last step.
Further progress done in js-waku to use several peers at the same times thanks to peer exchange, also roadmap for js-waku has been defined in more details.

**Comment by jm-clius** [comment]
Close as completed. Remaining work tracked in https://github.com/waku-org/pm/issues/67
