### ISSUE TITLE
[Epic] End-to-end testing

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#34]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**Epic label**: `E:End-to-end testing`

# Summary

- non regression (functional) testing as part of release cycle of nwaku,  go-waku and js-waku
- interoperability testing nwaku<>go-waku, js-waku<>nwaku, js-waku<>go-waku
- non regression (performance) testing as part of release cycle of nwaku, go-waku and js-waku

Work driven by the Vac/DST team

# Acceptance Criteria

- [ ] Test suite for the various service protocols
- Implement test suite as unit tests in the clients
	- [ ] js-waku
	- [ ] go-waku
	- [ ] nwaku
- [ ] Setup a separate integrated testing environment where these test cases (and others) can be run against a "blackbox" network, with configurable nwaku, go-waku, js-waku clients for regular regression testing.
	- [ ] go-waku
	- [ ] nwaku
	- [ ] js-waku
	- [ ] go-waku<>nwaku
	- [ ] js-waku<>nwaku
	- [ ] js-waku<>go-waku
- [ ] Add performance test to integrated environment (benchmark is done and comparison to benchmark as part of release process)

# Tasks

- [ ] go-waku: https://github.com/waku-org/go-waku/issues/608

**Comment by fryorcraken** [comment]
**monthly update**

[Work has started ](https://www.notion.so/Roadmap-Distributed-Systems-Testing-DST-4ef0d8694d3e40d6a0cfe706855c43e6#952f57c02c004ebc828f09f3e93abbeb) in the Vac/DST team with the new test analyst to write test plan for Waku protocols.

**Comment by jm-clius** [comment]
Closing, as this is replaced by https://github.com/waku-org/pm/issues/73

**Comment by fryorcraken** [comment]
Let's use that at the epic that tracks the DST testing part of #73

**Comment by chair28980** [comment]
@kaiserd are we safe to close this issue as we prioritize for 2024? Is this work tracked on the VAC side?
