### ISSUE TITLE
[Milestone] Support Many Platforms

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#42]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**This is a new milestone that was not initially identified**

**Milestone**: https://github.com/waku-org/pm/milestone/2

**Priority Tracks**: Growth
**Due date**: TBD

# Summary

To grow the Waku ecosystem, we need to ensure that the integration of Waku in any software of library is possible and friction-less.

# Justification

As an infrastructure project, Waku needs to be available in various languages and platform so that projects can integrate it easily, without having to deal with building or integration issues.

We are pushing js-waku first to project external to Logos/Status, so that web app developers, hackers and any one wanted to build a quick PoC can.
However, most serious/production adoption of Waku out there also use native system library: XMTP, TheGraph, Status.

To achieve this goal, we need to provide SDK and examples that demonstrate how Waku can be used with several languages and on several platforms.
Finally, community developers out there with limited dev resources will prioritize building single business logic libraries on top of Waku to use on all environment (mobile, node, desktop, web). We need to enable them to do so with Waku SDKs.

# Scope

Scope is yet to be defined.

The first step would be to define a number of languages and platforms. A community poll is tracked in https://github.com/waku-org/docs.waku.org/issues/107.

Once defined, for each platforms we should produce:
- a packaged SDK (as per language's best practices)
- a couple of example appropriate to the platform (e.g. relay vs light client)
- basic documentation for the given language.

Producing all 3 artefact above for the selected languages is the acceptance criteria for this milestone.

In addition to this, an exhaustive c-bindings and REST APIs enables willing developers to integrate Waku in any other non-supported languages.

As of Oct 2023:
- Scope is still yet to be defined
- Rust should be part of this because it is used by TheGraph and other parties such as Silent Labs are interested
- NodeJS should be part of this because it is used by RAILGUN and regularly requested.
- The community poll yield very little results, we need more user for better estimate.

# Epics

  - [ ] nwaku: [nwaku c-bindings](https://github.com/waku-org/nwaku/issues/1332)
  - [ ] nwaku: [HTTP REST API: Store, Filter, Lightpush, Admin and Private APIs](https://github.com/waku-org/nwaku/issues/1076)
  - [ ] go-waku: [C-Bindings Improvement: Callbacks and Duplications](https://github.com/waku-org/go-waku/issues/629)
  - [ ] go-waku: [HTTP REST API: Store, Filter, Lightpush, Admin and Private APIs](https://github.com/waku-org/go-waku/issues/264)

**Comment by fryorcraken** [comment]
**monthly update**

Several learnings on wrapping nim in another GC languages such as NodeJS. New recommended strategies are being implemented before we can release NodeJS and Python packages.

**Comment by fryorcraken** [comment]
Tentative due date set to 2024Q1 but will need to be revise once the scope is set.
