### ISSUE TITLE
[Epic] 2.1: Production testing of existing protocols

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#49]
**Epic label**: `E:2.1 Production testing of existing protocols`

# Summary

All service protocols are currently in alpha/beta implementation phase and have undergone significant changes aimed at delivering the Status MVP. Filter protocol, for example, has been redesigned from the ground up, while a new PostgreSQL archive backend for the Store protocol has been added. Before building on these protocols, their use in a production environment must be properly dogfooded and hardened.

# Acceptance Criteria

# Tasks

- [ ] nwaku: https://github.com/waku-org/nwaku/issues/1950
- [ ] nwaku: https://github.com/waku-org/nwaku/issues/1948
- [x] nwaku: https://github.com/waku-org/nwaku/issues/1888
- [ ] js-waku: https://github.com/waku-org/js-waku/issues/1463
- [x] js-waku: https://github.com/waku-org/js-waku/issues/914

**Comment by fryorcraken** [comment]
Revising due date from 31Aug to 30Nov because of strong dependency on Status to move forward with dogfooding.

**Comment by fryorcraken** [comment]
Regarding 30Nov timeline.
Remaining issues: https://github.com/orgs/waku-org/projects/2/views/2?filterQuery=label%3A%22E%3A2.1%3A+Production+testing+of+existing+protocols%22+is%3Aopen&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status

Mainly:
- PostgreSQL
- js-waku filter usage improvements
- dogfooding support

Hence 30 Nov seems feasible, with risk on Status not dogfooding and providing feedback within timeframe.
