### ISSUE TITLE
[Epic] 1.2: Autosharding for autoscaling

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#65]
# Summary

  

This epic tracks designing and implementing an autosharding strategy based on content topics and the design requirements established in 1.1. The first phase would likely be to launch with a limited number of shards (perhaps no more than 128?). More shards can be added as the network grows organically, perhaps using some "generation ID", that allows opening more shards with successive generations.

# Acceptance Criteria

# Tasks

- [x] https://github.com/waku-org/js-waku/issues/1501
- [x] https://github.com/waku-org/js-waku/issues/1712
- [x] https://github.com/waku-org/js-waku/issues/1500
- [x] https://github.com/waku-org/go-waku/issues/786
- [x] https://github.com/waku-org/js-waku/issues/1710
- [x] https://github.com/waku-org/nwaku/issues/2197
- [x] https://github.com/waku-org/nwaku/issues/2201
- [x] https://github.com/waku-org/js-waku/issues/1749

**Comment by fryorcraken** [comment]
Work completed in nwaku (minus a non-critical feature).
Still ongoing on js-waku and go-waku

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: added functions for validating content topic, determining shard index and pubsub topic for autosharding
- _next_: configure js-waku node to use either static or auto sharding
- _blocker_: need my PRs approved/merged. Also best to merge in other open PRs, especially https://github.com/waku-org/js-waku/pull/1697

**Comment by chaitanyaprem** [comment]
Work completed in go-waku.

**Comment by chair28980** [comment]
Unknown: How to handle prioritizing js-waku remaining issues in this epic.

**Comment by chair28980** [comment]
@chair28980 find the relevant issues for the following PRs and add to epic description:

https://github.com/waku-org/nwaku/pull/1854
https://github.com/waku-org/nwaku/pull/1856
https://github.com/waku-org/nwaku/pull/1857
https://github.com/waku-org/nwaku/pull/1983
https://github.com/waku-org/nwaku/pull/1795
