### ISSUE TITLE
[Epic] 1.4: Sharded peer management and discovery

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#67]
**Epic label:** `E:1.4: Sharded peer management and discovery`

# Summary

  

This epic tracks work necessary to allow applications to interact with shards in a transparent manner. Relay nodes should preferably be subscribed to the shards carrying the content topic(s) the application is interested in. Where this is not the case, the application should be able to interact with service peers within the shards it's interested in via a peer management scheme. The peer manager should be tracking peers from all public shards or be able to discover such peers on demand.

# Acceptance Criteria

# Tasks
- [x] nwaku: https://github.com/waku-org/nwaku/issues/1940
- [x] js-waku: https://github.com/waku-org/js-waku/issues/1505
- [x] js-waku: https://github.com/waku-org/js-waku/issues/1504
- [x] nwaku: https://github.com/waku-org/nwaku/issues/1941
- [x] go-waku: https://github.com/waku-org/go-waku/issues/727
- [x] go-waku: https://github.com/waku-org/go-waku/issues/680
- [x] go-waku: https://github.com/waku-org/go-waku/issues/679
- [x] go-waku: https://github.com/waku-org/go-waku/issues/678

**Comment by SionoiS** [comment]
Ok! Dropping my thoughts here.

Goal:
Keep a healthy mix of peers from different shards and capability support.

Input:
Peer scoring system (unrelated to GossipSub) would take as input the peers from discovery. Each peers has an ENR with shards subscribed to and capabilities.

State:
It maybe be useful to keep the score, I'm not sure yet. Other states should be kept like shard subscriptions and own capabilities.

Output:
This system's output would be decisions about which peer to connect OR disconnect from.

MVP:
Scoring "engine" implemented but no "rule" AKA all peers get the same score.

Future:
Adding bonus/malus to peer score based on "rules".
egg. +10 score for peers that support STORE on a shard I'm subscribed to.

**Comment by chair28980** [comment]
Deprecate named sharding and update lightpush client issues need to be re prioritized to next year.
