### ISSUE TITLE
[Epic] 3.2: Basic DoS protection in production

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#70]
**Epic label**: `E:3.2: Basic DoS protection in production`

# Summary

  

An RLN mechanism implemented and productionised, which includes: 
1. Initial membership mechanism (likely only for Status CCs and some trial users)
2. Rate limiting when specified bandwidth threshold is exceeded

This phase would include allowing applications to provide their own DoS protection mechanisms by opening a message validation API.

# Acceptance Criteria

- [x] RLN validation deployed and enabled on autosharding fleet (fleet has not been created yet, I believe, though SP has started the work here). This would give us a proto-Waku Network with autosharding and RLN rate limiting.
- [x] Membership for core contributors so "everyone" can start dogfooding (even if this is just a guide on how to register on the sepolia contract).
- [x] Ensuring messages can be published (via the client APIs) with RLN proof attached.
- [x] Limiting the number of memberships in the contract to an absolute maximum (10K for Gen 0)

# Tasks

- [x] go-waku: https://github.com/waku-org/go-waku/issues/732
- [x] go-waku: https://github.com/waku-org/go-waku/issues/731
- [x] go-waku: https://github.com/waku-org/go-waku/issues/655
- [x] https://github.com/waku-org/go-waku/issues/744
- [x] https://github.com/waku-org/pm/issues/51
- [x] https://github.com/waku-org/pm/issues/52
- [x] https://github.com/waku-org/pm/issues/55

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by DeBelg** [comment]
I had this one linked in my notes, https://github.com/waku-org/research/issues/20 @chair28980  is this same or part of this?

**Comment by chair28980** [comment]
> I had this one linked in my notes, https://github.com/waku-org/research/issues/20 @chair28980 is this same or part of this?

@DeBelg I think this specific issue tracks the tasks the epic depends on to ship, while #51 serves as a general tracking issue for dogfooding once all other epics/tasks are complete.

cc @jm-clius am I on base here?

**Comment by jm-clius** [comment]
Ah, I can see why this is confusing, but close enough. This is about the work that is necessary to productionise our DoS protection code. After this stage we may still have limited memberships, contract only on a testnet, etc. #51 looks towards a future where RLN has an open membership mechanism, mainnet contracts, etc. In other words dogfooding once everything else is done, as @chair28980 points out.

**Comment by DeBelg** [comment]
Thanks for clarifications!
