### ISSUE TITLE
[Epic] NodeJS Library

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#81]
**Planned start date**: 01Jul2023
**Due date**: TBD

# Summary

Provide a Waku NodeJS library targeting server environment

# Acceptance Criteria

- [ ] Working NodeJS library that can be used for service node purposes (ie store, relay, filter/lp server, discv5)
- [ ] Library is published on npmjs.com
- [ ] 2 NodeJS app examples
- [ ] Get started documentation

# Tasks

- [ ] NodeJS wrapper for nwaku https://github.com/waku-org/nwaku/issues/1332

# RAID (Risks, Assumptions, Issues and Dependencies)

- There are no example in the Nim ecosystem on how to wrap a nim library in a NodeJS package using c-bindings, without having both GC conflicting
- There may be a need to update the c-bindings RFC based on findings from this work.
