### ISSUE TITLE
[Epic] Simulation with 10k nodes

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#85]
**Epic label**: `E:...` (no label as the work is mainly tracked in Vac)
**Planned start date**:
**Due date**:

# Summary

The assumption to support 1 mil users #83 is that a given shard can support 10k users.
Simulations are needed to confirm that network and software behaviour are reasonable enough so a node can run on a home computer and connection

# Acceptance Criteria

- [ ] Simulation of a Waku Relay network with 10k active nodes
- [ ] Simulation of a Waku Relay network with 10k active nodes, where some nodes provide and consume store services
- [ ] Simulation of a Waku Relay network with 10k active nodes, where some nodes provide and consume filter and light push services

# Tasks

- https://github.com/vacp2p/research/issues/191

**Comment by fryorcraken** [comment]
@jm-clius @stubbsta this is tracked on DST side, right? Can we point to their tracker and close this?
