### ISSUE TITLE
[Epic] Automated Release processes

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#86]
**Epic label**: `E:Automated release processes`
**Planned start date**:
**Due date**:

# Summary

Setup automated release processes on all Waku clients.

# Acceptance Criteria

- release processes cost minimal effort and are not prone to manual error
- QA steps can easily be integrated to the release process
- Binaries and docker images are provided for popular architecture (when relevant)
- Publication on the relevant languages registry (language specific, e..g. npmjs.com)
- API Docs are automatically generated (if applicable)
- Changelog are automatically generated
- hot fix patches and out-of-schedule release can be done with minimum effort.
- nightly build or equivalent (if applicable) to enable integration and end-to-end testing and smaller feedback loop.

# Tasks

- [x] nwaku: https://github.com/waku-org/nwaku/issues/1889
- [x] js-waku: https://github.com/waku-org/js-waku/issues/1543
- [ ] waku-rust-bindings: https://github.com/waku-org/waku-rust-bindings/issues/67

**Comment by fryorcraken** [comment]
@waku-org/js-waku-developers @waku-org/go-waku-developers Keen to have your input on this before I set acceptance criteria.

See https://github.com/waku-org/nwaku/issues/1889

cc @vpavlin

**Comment by fryorcraken** [comment]
Feedback: 
- track effort to remove flackiness of tests

**Comment by fryorcraken** [comment]
> Feedback:
> 
>     * track effort to remove flackiness of tests

Tracked with https://github.com/waku-org/pm/issues/90
