### ISSUE TITLE
[Epic] Comprehensive Dev Testing

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#90]
**Epic label**: `E:Comprehensive dev testing`

# Summary

  

Epic to track testing effort (as done by Waku engineers) to ensure high quality software and stability.

This epic can be seen as a laundry that each client should review and extract action items if application to the client.

This excludes end-to-end testing effort (#34).

# Acceptance Criteria

- CI is stable with minimum false negative (no flacky CI)
- Target environments are included in the CI (e.g. Linux/Mac, browser/node, etc)
	-  waku-org/js-waku#52
- Test coverage is tracked and on target (if applicable, target to be set per client)
	- waku-org/go-waku#620
- Performance, low level system profiling, static analysis are setup and run as part of CI or release.
	- Memory profiling
	- Race condition analysis
	- Code maintainability
	- Static analysis

# Tasks

- [ ] js-waku: https://github.com/waku-org/js-waku/issues/1589
- [ ] js-waku: https://github.com/waku-org/js-waku/issues/1435
- [ ] js-waku: https://github.com/waku-org/js-waku/issues/337
- [ ] js-waku: https://github.com/waku-org/js-waku/issues/1595
- [ ] js-waku: https://github.com/waku-org/js-waku/issues/1597
