### ISSUE TITLE
Enhance Light Push

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#93]
# Summary

  

The Light Push protocol as [currently defined](https://rfc.vac.dev/spec/19/) is very bare.
After usage and implementations, the need of some features was raised:

- Returning errors _a la_ [filter](https://github.com/vacp2p/rfc/blob/master/content/docs/rfcs/12/README.md) with error code and description to clarify reason of failure:
 - service node does not have enough relay peer in this mesh for this pubsub topic
 - service node not subscrived to this pub sub topic
 - message pushed is invalid/malformed
 - timestamp out of range
 - (future) RLN proof is invalid (or could be same as above)
 - (future) this content topic is not served
- Returning information in case of success such as:
  - number of peers to whom the message was forwarded.

Considering the scope of change, backward compatibility should be possible and preferred

# Acceptance Criteria

- [x] Update RFC
- [x] Implement changes

# Tasks

- [x] Define lightpush protocol response new structure and possible error codes in the RFC
   - https://github.com/waku-org/specs/pull/20
- [ ] Redefine Lightpush response RPC and handle edge cases over relay.
   - https://github.com/waku-org/nwaku/issues/2722
   - [x] Update REST-API lightpush interface
- [x] Update REST-API specification

**Comment by chaitanyaprem** [comment]
Adding the additional error case which was identified during https://github.com/waku-org/nwaku/pull/2601 is
- In case messageSize crosses the configured network max-msg-size set for relay, respond with allowed messageSize

**Comment by fryorcraken** [comment]
What is the Status on that? is it done part of #70 ?

**Comment by Ivansete-status** [comment]
> What is the Status on that? is it done part of Req-Res DoS Protection? @Ivansete-status

Morning @fryorcraken! Thanks for the heads-up!
I think we have something done but I'm not sure about the actual implementation

@NagyZoltanPeter - Kindly share some insight about the implementation we did, if any. On the other hand, we need to create/link `nwaku` issues as a tasks of this `[Epic] Enhance light push protocol`, similarly as we are doing in the following epics:

- https://github.com/waku-org/pm/issues/141
- https://github.com/waku-org/pm/issues/147

Summarizing, if we haven't had the chance to look at it yet we need to create the necessary `nwaku` tasks, and link them to this epic, so that we can prioritize them from the `nwaku` PM sessions :)

Cheers

**Comment by NagyZoltanPeter** [comment]
> > What is the Status on that? is it done part of Req-Res DoS Protection? @Ivansete-status
> 
> Morning @fryorcraken! Thanks for the heads-up! I think we have something done but I'm not sure about the actual implementation
> 
> @NagyZoltanPeter - Kindly share some insight about the implementation we did, if any. On the other hand, we need to create/link `nwaku` issues as a tasks of this `[Epic] Enhance light push protocol`, similarly as we are doing in the following epics:
> 
> * [[Epic: nwaku] nwaku bindings #141](https://github.com/waku-org/pm/issues/141)
> * [[Epic: nwaku] PostgreSQL Maintenance #147](https://github.com/waku-org/pm/issues/147)
> 
> Summarizing, if we haven't had the chance to look at it yet we need to create the necessary `nwaku` tasks, and link them to this epic, so that we can prioritize them from the `nwaku` PM sessions :)
> 
> Cheers

@fryorcraken, @Ivansete-status: Honestly I don't remembe why this one is in-progress as we have not implemented these enhancement on error codes for lightpush (currently we are returning a text description of the error or "Ok"). 
Also to be enhanced the relay's publish does not really propagate errors, only the peers count that succeeded to relay to.
In the last release @shash256 implemented message size validation.
If that ok I will create the issues on nwaku repo and link them here. 

Also these are not in scope for DOS protection.

**Comment by fryorcraken** [comment]
This is part of #186 cc @chair28980
