### ISSUE TITLE
[Epic] Presentation Readiness 

### ISSUE THREAD

**Issue by weboko** [waku-org/pm#95]
**Epic label**: `E:Presentation Readiness`

# Summary

This epic created for tracking work items related to improvements for different consumer facing parts of Waku.  

Consumer could be: hacker, developer from project that uses Waku, node operator, regular documentation reader.

# Acceptance Criteria

- Address reported problematic parts
- Do feedback gathering sessions with various consumers

# Tasks

- [ ] https://github.com/waku-org/js-waku/issues/1666
- [ ] https://github.com/waku-org/js-waku/issues/1667
- [ ] https://github.com/waku-org/waku-ui/issues/26
- [ ] https://github.com/waku-org/docs.waku.org/issues/122
- [ ] https://github.com/waku-org/waku-ui/issues/27
- [ ] https://github.com/waku-org/js-waku/issues/1665

**Comment by fryorcraken** [comment]
Added to "support many platforms" for now. We may redefine the milestone to be more dev rel focused later.

**Comment by weboko** [comment]
Team agreed to keep working on this stream as following:
- collect items in this issue;
- create an umbrella issue for each repository if needed - to have separate discussions and tracking;
- @hackyguru will be reviewing items from this epic and making priority list for each of upcoming events;
- appropriate teams will prioritize these lists on its own;

cc @danisharora099 @vpavlin

**Comment by hackyguru** [comment]
this would be my priority list :

- https://github.com/waku-org/js-waku/issues/1666
- https://github.com/waku-org/waku-ui/issues/27
- https://github.com/waku-org/waku-ui/issues/26
- https://github.com/waku-org/js-waku-examples/issues/271
- https://github.com/waku-org/js-waku/issues/1665
- Add network diagrams  docs.waku.org#122
- https://github.com/waku-org/docs.waku.org/issues/127
- https://github.com/waku-org/js-waku/issues/1689
- https://github.com/waku-org/js-waku/issues/1667

this might make less sense but what i intend to say is we should make sure the initial docs for @waku/react go out and then we should work more around the pain points (subscription issues mostly) and then focus on improvements on store?

**Comment by weboko** [comment]
let's distribute tasks in this epic between `eco-dev` and `js-waku` teams so that we can plan and complete tasks in the upcoming months.

cc @waku-org/eco-dev @hackyguru @vpavlin @fryorcraken

**Comment by fryorcraken** [comment]
I think this can be reviewed in the context of the following milestones:
- https://github.com/waku-org/pm/issues/114
- https://github.com/waku-org/pm/issues/131

I would suggest doing an exercise to dispatch waht can be dispatched under those milestones.

The rest can just be `enhancement` issues.

**Comment by fryorcraken** [comment]
> this would be my priority list :
> 
>     * [feat: node connection state js-waku#1666](https://github.com/waku-org/js-waku/issues/1666)
> 
>     * [feat: hook to subscribe to events waku-react#27](https://github.com/waku-org/waku-react/issues/27
Part of https://github.com/waku-org/pm/issues/114

>     * [feat: hook to subscribe directly to filter or store waku-react#26](https://github.com/waku-org/waku-react/issues/26)

Part of https://github.com/waku-org/pm/issues/114

>     * [feat: example templates for fast development examples.waku.org#271](https://github.com/waku-org/examples.waku.org/issues/271)

Not sure about this, probably something @waku-org/eco-dev can take over

>     * [feat: better support for development js-waku#1665](https://github.com/waku-org/js-waku/issues/1665)

>     * Add network diagrams  [Add network diagrams  docs.waku.org#122](https://github.com/waku-org/docs.waku.org/issues/122)
> 
>     * [Expand Store protocol description docs.waku.org#127](https://github.com/waku-org/docs.waku.org/issues/127)
> 
>     * [chore: improve README.md js-waku#1689](https://github.com/waku-org/js-waku/issues/1689)
> 
>     * [feat: improve Store API js-waku#1667](https://github.com/waku-org/js-waku/issues/1667)
Could be part of https://github.com/waku-org/pm/issues/114
Could also be reviewed as part of https://github.com/waku-org/pm/issues/131
> 
> this might make less sense but what i intend to say is we should make sure the initial docs for @waku/react go out and then we should work more around the pain points (subscription issues mostly) and then focus on improvements on store?
