### ISSUE TITLE
[Epic] Targeted dogfooding for Status Communities

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#97]
**Epic label**: `E:Targeted Status Communities dogfooding`

# Summary

  

Dogfooding of delivery for Status Communities (static sharding, PostgreSQL, opt-in message signing).

# Acceptance Criteria

- [x] Fleet setup for Status staging https://github.com/waku-org/nwaku/issues/1914
- [x] Basic testing go-waku in Status Desktop + nwaku PostgreSQL/Static Sharding
- [x] Document Fleet maintenance to handover to Status https://github.com/waku-org/pm/issues/61

# Tasks

**Comment by fryorcraken** [comment]
@richard-ramos I think we can close https://github.com/waku-org/nwaku/issues/1914 so let's use this epic to track the work you are doing to test static sharding with Status Desktop.

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: hardcoded bootnodes ENRs in addition to DNS Discovery URLs as a way to overcome nameserver issues. Use a static shard instead of the default pubsub topic. 
- _next_:  fix if necessary strange behavior with discv5 when ENRs in DNS discovery URL do not contain shards. Document steps for dogfooding.

**Comment by fryorcraken** [comment]
@richard-ramos shared instructions on how to run Status Desktop with static sharding: https://discord.com/channels/1110799176264056863/1166125031793901589/1166125169480306708 (Waku Discord - private channel)

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: unsuccesfully tried to avoid introducing a [breaking change](https://github.com/status-im/status-go/pull/4161) in status-go. We need to decide whether to go ahead and merge that PR
- blocker: discv5 filters out outdated ENR entries from DNS Discovery URL in shard fleet -  https://github.com/waku-org/nwaku/issues/2162

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: fix in status-go to use correct unprotected pubsub topic for community point of contacts, added pubsub topic bridge feature to go-waku, stop filtering out bootnodes on discovery, minimize noise on logs when selecting peers and not having peers available.
- _next_: deploy bridge between default pubsub topic and shard 32

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: deployed bridge between default pubsub topic and shard 32, added `UseShardAsDefaultTopic` node config option to indicate whether the client should use a shard or the default waku topic. Merged open status-go PRs related to sharding. Updated open status-desktop PR for dogfooding to take into account status-go latest sharding related changes.
- _next_: get https://github.com/status-im/status-desktop/pull/12344 merged.

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: logout / login freeze, fix request on correct pubsub topic, and add missing shard information on community  invite
- _next_: dogfooding

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: fix pubsub topic used for store queries, logic for finding free port when initializing torrent service, add back changes related to default shard that were reverted before, store clusterID in app database, refactor mailserver cycle to not require having an active connection to a store node
- _next_: dogfooding

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: fix issue of using default clusterID as 16 for shards fleet, dogfooding of status-desktop with shards fleet, debug issues in connection to fleet
- _next_: continue dogfooding

**Comment by chaitanyaprem** [comment]
Interim report of dogfooding shards-fleet using status desktop by Waku Team

# Summary & Observations

- 5 CCs have participated in dogfooding the sharding fleet using various desktop builds (mac-aarch64, windows, linux) 
- 2 test Communities were created and assigned shards where participants have joined and sent messages and verified history retrieval. 1:1 messages were tested by various participants.
- Peer connectivity was verified to ensure healthy peer connections for the shard
- Fetching message history for community before a user joined
- Identified and fixed issues in status-go to work with sharding fleet (Refer below)
- Raised an issue wrt fleet config that is causing desktop not to connect with different store nodes https://github.com/status-im/infra-shards/issues/23
- Continue dogfooding once fleet config isssue is addressed

# Issues observed/Raised in status desktop

https://github.com/status-im/status-desktop/issues/12831
https://github.com/status-im/status-desktop/issues/12807

### UI related
https://github.com/status-im/status-desktop/issues/12746
https://github.com/status-im/status-desktop/issues/12745
https://github.com/status-im/status-desktop/issues/12744
https://github.com/status-im/status-desktop/issues/12743
https://github.com/status-im/status-desktop/issues/12742
https://github.com/status-im/status-desktop/issues/12741
https://github.com/status-im/status-desktop/issues/12740
https://github.com/status-im/status-desktop/issues/12738


# Issues resolved in status-go
https://github.com/status-im/status-go/pull/4370
https://github.com/status-im/status-go/pull/4368
https://github.com/status-im/status-go/pull/4363
https://github.com/status-im/status-go/pull/4362

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: fix peer manager to take into account the ENR seq to determine if a peer is new or not and fix incorrect number of connected peers per topic. Register lightpush protocol correctly in go-waku. Drop pubsub topic bridging. Use shards.test fleet as default (in status-go and desktop)
- _next_: continue dogfooding / fixing issues

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: status dogfooding, raise issues and optimizations needed wrt light protocols usage in status-go and improvements to be done in nwaku

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: fix panic on logout, publish messages async, fix loading message history for communities, fix invalid bootnodes being used on status desktop. 
- _next_: continue dogfooding / fixing issues

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: analyze and repro filter delay issue reported in mobile e2e automated test by dogfooding 
- _next_: continue status-mobile dogfooding with desktop / fixing issues

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: attempt to identify root cause of filter delay issue, work on upgrading status-go to use Go 1.21 (to use latest go-libp2p), use latest go-waku version and identify missing commits between release and `develop` branch
- _next_: continue dogfooding / fixing issues

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: status-mobile dogfooding, debug and attempt to identify root cause of filter delay issue
- _next_: continue dogfooding / fixing issues

**Comment by fryorcraken** [comment]
Waku dogfooding has concluded and Status QA has taken over testing.
Waku team is now providing support to Status testing.
